---
- name: Provision an EC2 node
  hosts: local
  connection: local
  gather_facts: False
  vars:
    keypair: personal
    instance_type: t2.micro
    security_group: base-group
    image: ami-
    region: us-east-1
  tasks:
    - name: Create security group
      local_action:
        module: ec2_group
        ec2_access_key:
        ec2_secret_key:
        name: base-group
        description: Access base-group
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

    - name: Starting Image master
      ec2:
        ec2_access_key:
        ec2_secret_key:
        instance_type: t2.micro
        image: ami-
        wait: yes
        wait_timeout: 500
        count: 1
        group: base-group
        monitoring: yes
        region: us-east-1
        instance_tags:
            Name: base-image
      register: ec2
    - name: Add instance to local host group
      local_action: lineinfile dest=hosts regexp="{{ item.public_dns_name }}" insertafter="[launched]" line="{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
      with_items: ec2.instances
    - name: Add instances to host group
      local_action: add_host hostname= groupname=base-group
      with_items: ec2.instances

    - name: Give everyone a minute
      pause: minutes=1
